version: '3.9'

services:
  app:
    container_name: ms-users
    image: ms-users
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 3000
    networks:
      - nginx_proxy_default
      - mongo_default

networks:
  nginx_proxy_default:
    external: true
  mongo_default:
    driver: bridge
